TypeScript
craftzdog/chat-bubbles-for-yt pull request #10
Opened 2023-02-22 12:09 UTC by peetzweg

Upgrades react and converts codebase to TypeScript.

2023-02-23 01:10 UTC, craftzdog commented
Thanks but there are a lot of TS errors. Can you clean them up?

2023-02-23 09:50 UTC, peetzweg commented
Added types throughout all files. ✌️

2023-02-24 01:48 UTC, craftzdog commented
No, this commit [b30371b](https://github.com/craftzdog/chat-bubbles-for-yt/pull/10/commits/b30371b84001c33a7244b0d2f31fc49ed958bb19) broke the animations.

2023-02-24 07:19 UTC, peetzweg commented
> No, this commit [b30371b](https://github.com/craftzdog/chat-bubbles-for-yt/pull/10/commits/b30371b84001c33a7244b0d2f31fc49ed958bb19) broke the animations.

Just pushed a fix. It was the missing `key` prop of the `<Bubble />`.
https://github.com/peetzweg/chat-bubbles-for-yt/blob/e6b7dd2a67d24f5986065971dcc3de5c8a4feb3c/src/App.tsx#L35

Weird though as component itself sets the `key` prop with the `id`. Guess my understanding of use of `key` in React is not yet complete. 🤔

2023-02-27 00:20 UTC, craftzdog requested changes

2023-02-27 00:20 UTC, craftzdog commented on src/use-messages.ts
> +      }, 3000)
Can you revert the timeout length to 15000?

2023-02-27 08:37 UTC, peetzweg commented on src/use-messages.ts
> +      }, 3000)
Oh! Good catch. Had it changed for debugging the flickering issue. Not intended to change it.

2023-02-28 00:30 UTC, merged

2023-02-28 00:30 UTC, craftzdog commented
Awesome! Thank you